name: Write Properties
description: Write properties to a properties file.
author: Christian Dräger
branding:
  icon: 'edit'
  color: 'yellow'
inputs:
  path:
    description: 'The path to the properties file.'
    required: true
  property:
    description: 'The property keys you want to write. Accepts an array.'
    required: true
  value:
    description: 'The property values you want to write (same order as the keys). Accepts an array.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.property }}
    - ${{ inputs.value }}
